# Generated by Django 2.2.4 on 2019-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_auto_20190818_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='author_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='author_id',
            field=models.ManyToManyField(to='libro.Author'),
        ),
    ]
