# Generated by Django 2.2.4 on 2019-08-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20190818_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='author_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libro.Author'),
            preserve_default=False,
        ),
    ]
