# Generated by Django 2.2.4 on 2019-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_auto_20190818_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='author_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='author_id',
            field=models.ManyToManyField(to='libro.Author'),
        ),
    ]
